config/routes.rb
Rails.application.routes.draw do
  root "videos#index"
  devise_for :users
  resources :users do
    collection do
      delete :destroy_session
    end
  end
  resources :videos do
    member do
      post :like
      post :dislike
      post :undo_react
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  enum status: %w[private_video public_video deleted]
  has_many :user_reacts
  has_many :user_videos
  has_many :shared_users, through: :user_videos
  validates_presence_of :url

  before_save :add_extra_data

  def add_extra_data
    self.youtube_data = get_data_from_youtube.merge({shared_email: user.email})
    self.title = self.youtube_data["title"]
  end

  def get_data_from_youtube
    youtube_id = ApplicationController.helpers.youtube_id(url)
    require "uri"
    require "net/http"

    url = URI("https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=#{youtube_id}&format=json")

    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)

    response = https.request(request)
    return {} unless response.code == "200"

    JSON.parse(response.read_body)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # before_action :redirect_to_login, except: %i[index]
  before_action :set_video, only: %i[ show edit update destroy ]
  before_action :set_my_video, only: %i[ edit update destroy ]

  # GET /videos or /videos.json
  def index
    @pagy, @videos = pagy(
      Video.all.order(created_at: :desc),
      items: 10
    )
    @user_reacts = UserReact.where(user: current_user, video_id: @videos.pluck(:id))
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = current_user.videos.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @my_video.update(video_params)
        format.html { redirect_to video_url(@my_video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @my_video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @my_video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    ReactVideoJob.perform_now(current_user.id, params[:id], "like")
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Liked." }
      format.html { }
    end
  end

  def dislike
    ReactVideoJob.perform_now(current_user.id, params[:id], "dislike")
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Disliked." }
      format.json { render json: { code: 0, status: "success" } }
    end
  end

  def undo_react
    user_react = UserReact.find_by(user_id: current_user.id, video_id: params[:id])
    json_response = { code: 0, status: "success" }
    if user_react.present?
      user_react.destroy
    else
      json_response = { code: 1, status: "failure", message: "cannot find react" }
    end
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Undo." }
      format.json { render json: json_response }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    def set_my_video
      @my_video = current_user.videos.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:url, :status)
    end

  def redirect_to_login
    redirect_to new_user_session_path unless current_user.present?
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "contents") do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, collection: %w[private_video public_video],
      class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/videos/_pager.html.erb
<div id="pager" class="min-w-full my-8 flex justify-center">
  <div>
    <% if pagy.next %>
      <%= link_to(
        "Load more videos",
        videos_path(page: pagy.next),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_frame: "page_handler",
          controller: "autoclick"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/videos/_react.html.erb
<% current_react = @user_reacts&.find_by(video_id: video.id) %>
<% if current_react.present? %>
  <div class="undo px-3">
    <%= form_for(video, url: undo_react_video_path(video), method: :post, remote: true) do |f| %>
      <div class="flex">
        <%= f.button raw("#{eval("#{current_react.kind}_voted_svg")}"),
                     type: "submit"
        %>
        <span class="ml-3"><%= current_react.kind == 'like' ? "(voted up)" : "(voted down)" %></span>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="like px-3">
    <%= form_for(video, url: like_video_path(video), method: :post, remote: true) do |f| %>
      <%= f.button raw(like_svg),
                   type: "submit"
      %>
    <% end %>
  </div>
  <div class="dislike px-3">
    <%= form_for(video, url: dislike_video_path(video), method: :post, remote: true) do |f| %>
      <%= f.button raw(dislike_svg),
                   type: "submit"
      %>
    <% end %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <div class="flex justify-center my-5">
    <div class="youtube-frame">
      <%= raw(youtube_embed(video.url)) %>
    </div>
    <div class="video-detail px-3">
      <p><%= video.title %></p>
      <div class="flex items-center justify-between">
        <div>
          <p>Shared by: <%= video.youtube_data["shared_email"] || video.youtube_data["author_name"] %></p>
          <div class="box-reacted flex items-center">
            <div class="like flex">
              <%= video.like %>
              <%= raw(like_voted_svg) %>
            </div>
            <div class="dislike flex px-3">
              <%= video.dislike %>
              <%= raw(dislike_voted_svg) %>
            </div>
          </div>
        </div>
        <div class="box-react flex items-center">
          <%= render partial: "react", locals: { video: video } %>
        </div>
      </div>
    </div>
  </div>


  <%# if action_name != "show" %>
    <%#= link_to "Show this video", video, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to 'Edit this video', edit_video_path(video), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
<!--    <hr class="mt-6">-->
  <%# end %>
</div>

app/views/videos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing video</h1>

  <%= render "form", video: @video %>

  <%= link_to "Show this video", @video, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to videos", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
    "append",
    target: "videos",
    template: %(#{render @videos}) 
  ) %>
  <%= turbo_stream_action_tag(
    "replace",
    target: "pager",
    template: %(#{render "pager", pagy: @pagy})
    ) %>
<% end %>

app/views/videos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= turbo_frame_tag "page_handler" %>
  <div id="videos" class="min-w-full">
    <%= render @videos %>
  </div>
  <%= render "pager", pagy: @pagy %>
</div>

app/views/videos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New video</h1>

  <%= render "form", video: @video %>

  <%= link_to 'Back to videos', videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @video %>

    <%= link_to 'Edit this video', edit_video_path(@video), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this video', video_path(@video), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to videos', videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>