config/routes.rb
Rails.application.routes.draw do
  root "videos#index"
  devise_for :users
  resources :users do
    collection do
      delete :destroy_session
    end
  end
  resources :videos do
    member do
      post :like
      post :dislike
      post :undo_react
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
<div class="container mt-3 mx-auto flex justify-between items-center">
  <div class="">
    <%= link_to "FUNNY VIDEOS", root_path %>
  </div>
  <div class="flex items-center">
    <% if current_user.present? %>
      <p class=""><%= "Hello, #{current_user.email}" %></p>
      <%= link_to "Share a movie",
                  new_video_path,
                  class: "ml-2 rounded-lg py-2 px-3 bg-blue-600 text-white block"
      %>
      <%= button_to "Log out",
                    :destroy_session_users,
                    class: "ml-2 rounded-lg py-2 px-3 bg-gray-600 text-white block",
                    method: :delete,
                    'data-no-turbolink' => true
      %>
    <% else %>
      <%= form_for(User.new, as: :user, url: session_path(:user), html: {class: "ml-2"}) do |f| %>
        <div class="flex items-center">
          <div class="field ml-2">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", id: "login-email" %>
          </div>

          <div class="field ml-2">
            <%= f.password_field :password, autocomplete: "current-password", id: "login-password" %>
          </div>

          <div class="actions ml-2">
            <%= f.submit "Log in", class: "rounded-lg py-2 px-3 bg-blue-600 text-white block" %>
          </div>
          <%= link_to "Register", :new_user_registration, class: "ml-2 rounded-lg py-2 px-3 bg-gray-600 text-white block" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunVideos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section id="header">
      <%= render partial: "layouts/header" %>
    </section>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>